services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - 3306:3306

  web:
    container_name: django-web
    build:
      context: ./  # Đường dẫn đến thư mục backend
      dockerfile: Dockerfile
    command: python manage.py runserver 192.168.44.128:8000
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db

  nextjs:
    container_name: nextjs-web
    build:
      context: ../nail-fe  # Đường dẫn đến thư mục chứa Next.js
      dockerfile: Dockerfile  # Dockerfile của Next.js
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    volumes:
      - ../nail-fe:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - web  # Phụ thuộc vào Django
    links:
      - web

  nginx:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - 80:80  # Expose Nginx trên cổng 80
    volumes:
      - ../nail-fe/nginx.conf:/etc/nginx/nginx.conf  # Gắn cấu hình Nginx vào container
    depends_on:
      - nextjs
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
