
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=nail
      - MYSQL_ROOT_PASSWORD=Assa1234!!
    ports:
      - '3307:3306'
    expose:
      - 3306
  backend:
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db
    ports:
      -8080:8080