# Generated by Django 5.1.1 on 2024-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0002_alter_carts_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_payment',
        ),
        migrations.AddField(
            model_name='carts',
            name='price',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
