# Generated by Django 5.1.1 on 2024-10-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0005_alter_orders_city_code_alter_orders_district_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
