# Generated by Django 5.1.1 on 2024-10-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0006_orders_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
