# Generated by Django 5.1.1 on 2024-10-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0007_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
    ]
