# Generated by Django 5.1.1 on 2024-10-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0009_city_alter_orders_status_district_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='province_code',
        ),
    ]
